name: lompreydesign
favicon: null
layout_spectrum: 0.9765
typography_spectrum: 0.93594
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#716a58'
    - '#1b1603'
    - '#31bfc0'
    - '#fc4d1f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
