name: stevelomprey
favicon: null
layout_spectrum: 0.1941
typography_spectrum: 0.93594
title: lompreydesign
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7095760183874518
  lightness: 0.9739055340178311
  saturation: 0.13022208702750504
  rhythmicContrast: 0.7543174442835152
purpose: []
